# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: yarn CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn versions
      - run: yarn install --frozen-lockfile
      - run: yarn run test
      #- uses: borales/actions-yarn@v2.0.0
      #  with:
      #    cmd: build # will run `yarn build` command
      #- name: Install chromium-browser
      #  run: sudo apt-get update && sudo apt-get -y install chromium-browser
